name: Deploy to Dokku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DOKKU_DEPLOY_KEY }}
          github-deploy-key: false

      - name: Verify SSH key
        run: |
          echo "Verifying SSH key..."
          ssh-add -l -E md5
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -v dokku@${{ secrets.DOKKU_HOST }} "echo SSH connection successful!"

      - name: Deploy to Dokku
        run: |
          echo "Starting deployment..."
          echo "Copying files to server..."
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -v" ./web root@${{ secrets.DOKKU_HOST }}:/tmp/retrieval-demo
          echo "Running deployment commands..."
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -v root@${{ secrets.DOKKU_HOST }} << 'EOF'
            set -ex
            echo 'Changing to /tmp/retrieval-demo...'
            cd /tmp/retrieval-demo
            echo 'Building Docker image...'
            docker build -t dokku/retrieval-demo:latest .
            echo 'Deploying to Dokku...'
            dokku git:from-image retrieval-demo dokku/retrieval-demo:latest
            echo 'Cleaning up...'
            rm -rf /tmp/retrieval-demo
            echo 'Deployment complete!'
          EOF
