name: Build and Deploy to Dokku

on:
  push:
    branches: [main]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Generate unique tag
        id: tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Web Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-demo-web:${{ steps.tag.outputs.tag }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-demo-web:latest
          build-args: |
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
            NODE_ENV=production
            API_URL=${{ secrets.API_URL }}
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Generate unique tag
        id: tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-demo-back:${{ steps.tag.outputs.tag }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-demo-back:latest
          build-args: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
            VOYAGE_API_KEY=${{ secrets.VOYAGE_API_KEY }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build-web, build-backend]
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DOKKU_DEPLOY_KEY }}

      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
          git_remote_url: ${{ secrets.DOKKU_REMOTE_URL }}
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
