name: Build and Deploy to Dokku

on:
  push:
    branches: [main]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Web Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-demo-web:latest

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-demo-back:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-web, build-backend]
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DOKKU_DEPLOY_KEY }}
          github-deploy-key: false

      - name: Deploy to Dokku
        run: |
          echo "Starting deployment..."
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -v root@${{ secrets.DOKKU_HOST }} << 'EOF'
            set -ex
            echo 'Deploying Web app...'
            dokku git:from-image retrieval-demo ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-demo-web:latest || true
            
            echo 'Deploying Backend app...'
            dokku git:from-image retrieval-demo-back ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-demo-back:latest || true

            echo 'Deployment complete!'
          EOF
