name: Build and Deploy to Dokku

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-web:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DOKKU_DEPLOY_KEY }}
          github-deploy-key: false

      - name: Deploy to Dokku
        run: |
          echo "Starting deployment..."
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -v root@${{ secrets.DOKKU_HOST }} << 'EOF'
            set -ex
            echo 'Pulling Docker image...'
            echo 'Pulling Web Docker image...'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-web:latest
            echo 'Deploying Web to Dokku...'
            dokku git:from-image retrieval-web ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-web:latest

            echo 'Pulling API Docker image...'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-api:latest
            echo 'Deploying API to Dokku...'
            dokku git:from-image retrieval-api ${{ secrets.DOCKER_HUB_USERNAME }}/retrieval-api:latest

            echo 'Setting up network...'
            dokku proxy:ports-set retrieval-web http:80:3000
            dokku proxy:ports-set retrieval-api http:80:8000
            dokku domains:set retrieval-web retrieval.rethoriq.com
            dokku domains:set retrieval-api api.retrieval.rethoriq.com
            dokku config:set retrieval-web API_URL=https://api.retrieval.rethoriq.com
            echo 'Deployment complete!'
          EOF
