name: Deploy to Dokku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t retrieval-demo:latest ./web

      - name: Save Docker image
        run: docker save -o retrieval-demo.tar retrieval-demo:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}

      - name: Copy image to server
        run: |
          scp -o StrictHostKeyChecking=no retrieval-demo.tar root@139.59.228.93:/tmp/retrieval-demo.tar

      - name: Load and deploy image on Dokku
        run: |
          ssh -o StrictHostKeyChecking=no root@139.59.228.93 << 'EOF'
          docker load -i /tmp/retrieval-demo.tar
          docker tag retrieval-demo:latest dokku/retrieval-demo:latest
          dokku tags:deploy retrieval-demo latest
          rm /tmp/retrieval-demo.tar
          EOF
