name: Deploy to Dokku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
          github-deploy-key: false

      - name: Deploy to Dokku
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ${{ secrets.DOKKU_DEPLOY_KEY }}" ./web root@${{ secrets.DOKKU_HOST }}:/tmp/retrieval-demo &&
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ${{ secrets.DOKKU_DEPLOY_KEY }} root@${{ secrets.DOKKU_HOST }} "
            set -e &&
            cd /tmp/retrieval-demo &&
            docker build -t dokku/retrieval-demo:latest . &&
            dokku git:from-image retrieval-demo dokku/retrieval-demo:latest &&
            rm -rf /tmp/retrieval-demo
          "
